services:
  chrome:
    image: kasmweb/chrome:1.16.0
    restart: unless-stopped
    shm_size: 2g                 # 解决Chromium崩溃/卡顿
    environment:
      - VNC_PW=${KASM_VNC_PW:-changeme_please}  # Web界面登陆密码
      - KASM_PORT=6901
      - SSL=false                # 由前置Nginx终止TLS
    ports:
      - "6901:6901"    # 仅本机暴露
