services:
  ttyd:
    image: ghcr.io/kun-g/chromes-work-env:v1.1.0
    command: ["/usr/bin/ttyd", "-W", "-p", "7681", "-c", "admin:${TTYD_PASSWORD:-changeme}", "bash"]
    environment:
      - NETBIRD_KEY=${NETBIRD_KEY}  # NetBird setup key
    cap_add:
      - NET_ADMIN    # NetBird 需要的网络权限
      - SYS_ADMIN
    ports:
      - "7681:7681"  # 不直接暴露，通过nginx访问
    volumes:
      - ./data:/home/dev
      - /dev/net/tun:/dev/net/tun  # NetBird 需要的 TUN 设备
    working_dir: /home/dev
    restart: unless-stopped
    networks:
      - internal
    
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    command: ["--config=/oauth2-proxy.cfg"]
    environment:
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET} # 32字节base64
      OAUTH2_PROXY_OIDC_ISSUER_URL: ${OAUTH2_PROXY_OIDC_ISSUER_URL}
    volumes:
      - ./oauth2-proxy.cfg:/oauth2-proxy.cfg:ro
    restart: unless-stopped
    networks:
      - internal

  nginx:
    image: nginx:1.25-alpine
    depends_on: [oauth2-proxy, ttyd]
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8443:443"
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    driver: bridge
